categories:
  social_media_marketing:
    - instagram
    - reels
    - tiktok
    - x
    - twitter
    - linkedin
    - threads
    - social media
    - influencer
    - ugc
    - community
  content_marketing:
    - content marketing
    - blog
    - newsletter
    - email
    - copywriting
    - storytelling
    - short-form
    - long-form
  seo:
    - seo
    - search
    - google
    - rank
    - keyword
    - backlink
    - sem
    - search console
    - core update
  paid_media:
    - ads
    - ppc
    - cpc
    - meta ads
    - google ads
    - performance max
    - retargeting
  analytics_ai:
    - ai
    - gen ai
    - chatgpt
    - gpt
    - attribution
    - data
    - analytics
    - ga4
  ecommerce:
    - shopify
    - conversion
    - cro
    - checkout
    - cart
    - ab test
    - lifetime value
  branding_pr:
    - branding
    - brand
    - pr
    - rebrand
    - positioning
  video_audio:
    - video
    - shorts
    - youtube
    - podcast
    - spotify
  local_international:
    - local seo
    - maps
    - gmb
    - international seo
    - hreflang
  privacy_compliance:
    - privacy
    - cookie
    - gdpr
    - ccpa
    - consent
